dist: trusty
sudo: required

language: java
jdk:
  - openjdk8
  - oraclejdk8

branches:
  except:
    - "/^v|d\\d+\\.\\d+\\.\\d+$/"
    - "/^jenkins-jhove-v|d\\d+\\.\\d+\\.\\d+$/"

install: mvn clean package

before_install:
  - sudo apt-get install -y jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar http://resources.openpreservation.org/codacy-coverage-reporter-assembly-latest.jar
